version: '3.8'

services:
  # Next.js Application (Production)
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # Database
      DATABASE_URL: ${DATABASE_URL}
      
      # NextAuth
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      
      # App Config
      APP_BASE_URL: ${APP_BASE_URL}
      ORS_API_SECRET: ${ORS_API_SECRET}
      
      # SMS & Maps
      SMSIR_API_KEY: ${SMSIR_API_KEY}
      NEXT_PUBLIC_NESHAN_MAP_KEY: ${NEXT_PUBLIC_NESHAN_MAP_KEY}
      NEXT_PUBLIC_NESHAN_API_KEY: ${NEXT_PUBLIC_NESHAN_API_KEY}
      
      # Environment
      NODE_ENV: "production"
      PORT: 3000
    
    # Health check
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
