name: Deploy to Liara

on:
  workflow_run:
  workflows: ["Build and Push MrShoofer Docker Image"]
  types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    env:
      LIARA_APP: mrshoofer-client

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy Docker Image to Liara (prefer SHA tag)
      env:
        FULL_SHA: ${{ github.event.workflow_run.head_sha }}
      run: |
        set -e
        IMAGE_BASE="sadradorostkar/mrshoofer-client"
        PREFERRED_TAG="sha-${FULL_SHA}"
        echo "Attempting deploy with tag: ${PREFERRED_TAG}"
        if npx @liara/cli deploy --platform docker --app ${LIARA_APP} --port 3000 --image ${IMAGE_BASE}:${PREFERRED_TAG} --no-app-logs --api-token "${{ secrets.LIARA_API_TOKEN }}"; then
          echo "Deployed ${IMAGE_BASE}:${PREFERRED_TAG}"
        else
          echo "SHA-tag deploy failed; falling back to :latest"
          npx @liara/cli deploy --platform docker --app ${LIARA_APP} --port 3000 --image ${IMAGE_BASE}:latest --no-app-logs --api-token "${{ secrets.LIARA_API_TOKEN }}"
        fi
